import stacks

s = stacks.Stack()
print ("isEmpty=%s" % s.isEmpty())
s.push(4)
s.push(5)
s.push(True)
s.push('cat')
print ("isEmpty=%s" % s.isEmpty())
print ("peek=%s" % s.peek())
s.pop()
s.pop()
print ("peek=%s" % s.peek())
print ("size=%d" % s.size())
s.push(12)
s.push(3)
s.push(4)
s.push(2)
s.push(1)
s.push(9)
print ("size=%d" % s.size())
s.sort()
while not s.isEmpty():
    print (s.pop())